In [1]:
!pip install gensim

Defaulting to user installation because normal site-packages is not writeable
  Obtaining dependency information for gensim from https://files.pythonhosted.org/packages/10/c3/7e22d6f7d88c4ea6a3a84481f00538252659d285713c3b7e2e1537b0e7e1/gensim-4.4.0-cp311-cp311-win_amd64.whl.metadata
  Obtaining dependency information for smart_open>=1.8.1 from https://files.pythonhosted.org/packages/b4/bd/1c92e69a1daff70118f21e18ef3a100c114f00f08b64a1074484f12d9020/smart_open-8.0.0-py3-none-any.whl.metadata
  Obtaining dependency information for wrapt from https://files.pythonhosted.org/packages/7e/9c/23695baa331c6de4e874c3d78b8e0bed92e1d2a274e665b29858f6841672/wrapt-2.2.2-cp311-cp311-win_amd64.whl.metadata
   ---------------------------------------- 0.0/24.4 MB ? eta -:--:--
   ---------------------------------------- 0.0/24.4 MB 660.6 kB/s eta 0:00:37
   ---------------------------------------- 0.0/24.4 MB 393.8 kB/s eta 0:01:02
   ---------------------------------------- 0.1/24.4 MB 901.1 kB/s eta 0


[notice] A new release of pip is available: 23.2.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [1]:
import gensim

In [2]:
from gensim.models import Word2Vec, KeyedVectors

In [5]:
import gensim.downloader as api
wv = api.load('word2vec-google-news-300')
vec_king = wv['king']

[==================================================] 100.0% 1662.8/1662.8MB downloaded


In [6]:
vec_king

array([ 1.25976562e-01,  2.97851562e-02,  8.60595703e-03,  1.39648438e-01,
       -2.56347656e-02, -3.61328125e-02,  1.11816406e-01, -1.98242188e-01,
        5.12695312e-02,  3.63281250e-01, -2.42187500e-01, -3.02734375e-01,
       -1.77734375e-01, -2.49023438e-02, -1.67968750e-01, -1.69921875e-01,
        3.46679688e-02,  5.21850586e-03,  4.63867188e-02,  1.28906250e-01,
        1.36718750e-01,  1.12792969e-01,  5.95703125e-02,  1.36718750e-01,
        1.01074219e-01, -1.76757812e-01, -2.51953125e-01,  5.98144531e-02,
        3.41796875e-01, -3.11279297e-02,  1.04492188e-01,  6.17675781e-02,
        1.24511719e-01,  4.00390625e-01, -3.22265625e-01,  8.39843750e-02,
        3.90625000e-02,  5.85937500e-03,  7.03125000e-02,  1.72851562e-01,
        1.38671875e-01, -2.31445312e-01,  2.83203125e-01,  1.42578125e-01,
        3.41796875e-01, -2.39257812e-02, -1.09863281e-01,  3.32031250e-02,
       -5.46875000e-02,  1.53198242e-02, -1.62109375e-01,  1.58203125e-01,
       -2.59765625e-01,  

In [7]:
vec_king.shape

(300,)

In [8]:
wv['cricket']

array([-3.67187500e-01, -1.21582031e-01,  2.85156250e-01,  8.15429688e-02,
        3.19824219e-02, -3.19824219e-02,  1.34765625e-01, -2.73437500e-01,
        9.46044922e-03, -1.07421875e-01,  2.48046875e-01, -6.05468750e-01,
        5.02929688e-02,  2.98828125e-01,  9.57031250e-02,  1.39648438e-01,
       -5.41992188e-02,  2.91015625e-01,  2.85156250e-01,  1.51367188e-01,
       -2.89062500e-01, -3.46679688e-02,  1.81884766e-02, -3.92578125e-01,
        2.46093750e-01,  2.51953125e-01, -9.86328125e-02,  3.22265625e-01,
        4.49218750e-01, -1.36718750e-01, -2.34375000e-01,  4.12597656e-02,
       -2.15820312e-01,  1.69921875e-01,  2.56347656e-02,  1.50146484e-02,
       -3.75976562e-02,  6.95800781e-03,  4.00390625e-01,  2.09960938e-01,
        1.17675781e-01, -4.19921875e-02,  2.34375000e-01,  2.03125000e-01,
       -1.86523438e-01, -2.46093750e-01,  3.12500000e-01, -2.59765625e-01,
       -1.06933594e-01,  1.04003906e-01, -1.79687500e-01,  5.71289062e-02,
       -7.41577148e-03, -

In [9]:
wv.most_similar('cricket')

[('cricketing', 0.8372225761413574),
 ('cricketers', 0.8165745735168457),
 ('Test_cricket', 0.8094819188117981),
 ('Twenty##_cricket', 0.8068488240242004),
 ('Twenty##', 0.7624265551567078),
 ('Cricket', 0.75413978099823),
 ('cricketer', 0.7372578382492065),
 ('twenty##', 0.7316356897354126),
 ('T##_cricket', 0.7304614186286926),
 ('West_Indies_cricket', 0.6987985968589783)]

In [10]:
wv.most_similar('happy')


[('glad', 0.7408890724182129),
 ('pleased', 0.6632170677185059),
 ('ecstatic', 0.6626912355422974),
 ('overjoyed', 0.6599286794662476),
 ('thrilled', 0.6514049172401428),
 ('satisfied', 0.6437949538230896),
 ('proud', 0.636042058467865),
 ('delighted', 0.627237856388092),
 ('disappointed', 0.6269949674606323),
 ('excited', 0.6247665286064148)]

In [11]:
wv.similarity("hockey","sports")

np.float32(0.5354152)

In [12]:
vec=wv['king']-wv['man']+wv['women']

In [13]:
vec

array([-0.33984375,  0.06298828, -0.00994873,  0.3305664 ,  0.10327148,
       -0.25854492,  0.19677734, -0.32476807, -0.15917969,  0.45752716,
       -0.39208984, -0.22460938,  0.02929688,  0.31982422, -0.0958252 ,
       -0.05932617,  0.01855469, -0.03945923,  0.01101685,  0.33984375,
        0.10351562,  0.14396667, -0.07641602,  0.06640625, -0.10839844,
       -0.1953125 , -0.3564453 , -0.02124023, -0.16503906, -0.16247559,
       -0.05519104, -0.1003418 ,  0.01464844,  0.23449707, -0.26611328,
       -0.07080078, -0.26904297, -0.00292969, -0.06738281, -0.02050781,
        0.04418945, -0.09326172,  0.12304688,  0.10626221,  0.10290527,
        0.01660156, -0.10791016, -0.0065918 ,  0.17578125,  0.10028076,
        0.22363281, -0.05761719, -0.31743622,  0.3922119 , -0.35498047,
       -0.23643494, -0.01074219, -0.01334572, -0.15283203, -0.00793457,
        0.08203125,  0.09985352,  0.003479  ,  0.11608887,  0.14550781,
       -0.125     , -0.11254883,  0.2548828 , -0.04345703,  0.34

In [14]:
wv.most_similar([vec])

[('king', 0.6478992700576782),
 ('queen', 0.535493791103363),
 ('women', 0.5233659148216248),
 ('kings', 0.5162314772605896),
 ('queens', 0.4995364248752594),
 ('kumaris', 0.49238473176956177),
 ('princes', 0.46233269572257996),
 ('monarch', 0.45280295610427856),
 ('monarchy', 0.4293173849582672),
 ('kings_princes', 0.42342400550842285)]

In [3]:
import pandas as pd
messages=pd.read_csv('SMSSpamCollection.csv', sep=',',names=["label","message"])

In [4]:
from nltk.stem import WordNetLemmatizer
lemmatizer=WordNetLemmatizer()

In [5]:
## Data cleaning and preprocessing
import re
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\sonup\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [6]:
corpus=[]
for i in range(0,len(messages)):
    review=re.sub('[^a-zA-Z]',' ',messages['message'][i])
    review=review.lower()
    review=review.split()
    review = [lemmatizer.lemmatize(word) for word in review]
    review=' '.join(review)
    corpus.append(review)

In [49]:
[[i,j,k] for i,j,k in zip(list(map(len,corpus)),corpus,messages['message']) if i<1]

[]

In [7]:
corpus

['go until jurong point crazy available only in bugis n great world la',
 'ok lar joking wif u oni',
 'free entry in a wkly comp to win fa cup final ticket text win to now',
 'u dun say so early hor u c already then say',
 'nah i don t think he go to usf he life around here though',
 'freemsg hey there darling it s been week now and no word back',
 'even my brother is not like to speak with me',
 'a per your request your callertune ha been activated',
 'congratulation you have won a walmart gift card reply claim',
 'are we still meeting for lunch today',
 'urgent your mobile number ha won cash prize',
 'can you pick up some milk on your way home',
 'you have been selected for a free vacation call now',
 'i ll call you later when i reach home',
 'exclusive offer buy get free limited time only',
 'don t forget to bring your notebook tomorrow',
 'win a brand new iphone text apple to',
 'thanks for helping me with the assignment',
 'your loan ha been approved contact u immediately',
 'i m 

In [50]:
from nltk import sent_tokenize
from gensim.utils import simple_preprocess

In [51]:
words=[]
for sent in corpus:
    sent_token=sent_tokenize(sent)
    for sent in sent_token:
        words.append(simple_preprocess(sent))

In [52]:
words

[['go',
  'until',
  'jurong',
  'point',
  'crazy',
  'available',
  'only',
  'in',
  'bugis',
  'great',
  'world',
  'la'],
 ['ok', 'lar', 'joking', 'wif', 'oni'],
 ['free',
  'entry',
  'in',
  'wkly',
  'comp',
  'to',
  'win',
  'fa',
  'cup',
  'final',
  'ticket',
  'text',
  'win',
  'to',
  'now'],
 ['dun', 'say', 'so', 'early', 'hor', 'already', 'then', 'say'],
 ['nah',
  'don',
  'think',
  'he',
  'go',
  'to',
  'usf',
  'he',
  'life',
  'around',
  'here',
  'though'],
 ['freemsg',
  'hey',
  'there',
  'darling',
  'it',
  'been',
  'week',
  'now',
  'and',
  'no',
  'word',
  'back'],
 ['even', 'my', 'brother', 'is', 'not', 'like', 'to', 'speak', 'with', 'me'],
 ['per', 'your', 'request', 'your', 'callertune', 'ha', 'been', 'activated'],
 ['congratulation',
  'you',
  'have',
  'won',
  'walmart',
  'gift',
  'card',
  'reply',
  'claim'],
 ['are', 'we', 'still', 'meeting', 'for', 'lunch', 'today'],
 ['urgent', 'your', 'mobile', 'number', 'ha', 'won', 'cash', 'prize

In [53]:
import gensim

In [54]:
## lets train word2vec from scratch
model=gensim.models.Word2Vec(words)

In [55]:
## to get all the vocabulary
model.wv.index_to_key

['you',
 'the',
 'your',
 'free',
 'for',
 'now',
 'have',
 'to',
 'won',
 'been',
 'get',
 'today',
 'ha',
 'me',
 'in',
 'am',
 'are',
 'claim',
 'gift',
 'win',
 'let',
 'will',
 'tomorrow',
 'offer',
 'call',
 'can',
 'cash',
 'available']

In [56]:
model.corpus_count

103

In [57]:
model.epochs

5

In [58]:
model.wv.similar_by_word('won')

[('available', 0.2852645516395569),
 ('your', 0.1994498372077942),
 ('win', 0.09671062231063843),
 ('free', 0.07499343901872635),
 ('now', 0.060777872800827026),
 ('been', 0.04491269215941429),
 ('today', 0.038229793310165405),
 ('cash', 0.03529460355639458),
 ('the', 0.033792588859796524),
 ('you', 0.027570612728595734)]

In [59]:
model.wv.similar_by_word('claim')


[('in', 0.24679359793663025),
 ('gift', 0.11968827992677689),
 ('to', 0.1196475476026535),
 ('me', 0.11728177219629288),
 ('get', 0.09611615538597107),
 ('call', 0.08813843876123428),
 ('the', 0.0854528620839119),
 ('cash', 0.07603998482227325),
 ('now', 0.0728444829583168),
 ('today', 0.06038469821214676)]

In [60]:
model.wv['claim'].shape

(100,)

In [61]:
words[0]

['go',
 'until',
 'jurong',
 'point',
 'crazy',
 'available',
 'only',
 'in',
 'bugis',
 'great',
 'world',
 'la']

In [62]:
import numpy as np

In [63]:
def avg_word2vec(doc):
    # remove out-of-vocabulary words
    sent = [word for word in doc if word in model.wv.index_to_key]
    
    if len(sent) == 0:
        # handle empty case gracefully
        return np.zeros(model.vector_size)
    
    return np.mean([model.wv[word] for word in sent], axis=0)


In [35]:
!pip install tqdm

Defaulting to user installation because normal site-packages is not writeable



[notice] A new release of pip is available: 23.2.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [36]:
from tqdm import tqdm

In [37]:
## apply for entire sentences

x=[]
for i in tqdm(range(len(words))):
    x.append(avg_word2vec(words[i]))

100%|██████████| 103/103 [00:00<00:00, 11444.36it/s]


In [38]:
x

[array([ 4.9058748e-03,  7.4276323e-03, -4.9026095e-04, -2.5762797e-03,
         8.4345844e-03, -1.6555474e-03,  6.0211276e-03, -1.1745242e-03,
         8.1317378e-03, -2.3035975e-03,  7.1459198e-03, -9.5994147e-03,
        -3.6690431e-03, -2.9472797e-03, -5.6876712e-03,  3.3675181e-04,
         7.7664861e-03, -5.0751660e-03, -7.2944991e-04,  2.2445023e-03,
         4.3193786e-04,  7.2049974e-03,  3.2995766e-04,  3.8850086e-04,
        -5.1207566e-03, -3.3002696e-04, -3.7483335e-03, -1.6133809e-03,
         1.3670819e-03, -3.5632788e-03, -5.1721279e-04, -4.9495874e-03,
        -3.0919111e-03, -5.9513114e-03, -6.0450677e-03, -8.6689517e-03,
         4.0581552e-03,  8.4339967e-03,  3.8694122e-03,  1.0452631e-03,
        -9.0916641e-05, -1.5222627e-03, -1.3253617e-03, -6.5038144e-04,
        -4.3336931e-04,  5.1391781e-03, -6.1555412e-03, -4.6909205e-04,
         1.5812786e-03,  4.7753882e-03,  6.4239150e-04, -2.3371857e-03,
         4.9051894e-03, -7.1727578e-03,  8.5053523e-04, -2.63266

In [64]:
len(x)

103

In [65]:
##independent features
x_new=np.array(x)

In [66]:
x_new.shape

(103, 100)

In [68]:
x

[array([ 4.9058748e-03,  7.4276323e-03, -4.9026095e-04, -2.5762797e-03,
         8.4345844e-03, -1.6555474e-03,  6.0211276e-03, -1.1745242e-03,
         8.1317378e-03, -2.3035975e-03,  7.1459198e-03, -9.5994147e-03,
        -3.6690431e-03, -2.9472797e-03, -5.6876712e-03,  3.3675181e-04,
         7.7664861e-03, -5.0751660e-03, -7.2944991e-04,  2.2445023e-03,
         4.3193786e-04,  7.2049974e-03,  3.2995766e-04,  3.8850086e-04,
        -5.1207566e-03, -3.3002696e-04, -3.7483335e-03, -1.6133809e-03,
         1.3670819e-03, -3.5632788e-03, -5.1721279e-04, -4.9495874e-03,
        -3.0919111e-03, -5.9513114e-03, -6.0450677e-03, -8.6689517e-03,
         4.0581552e-03,  8.4339967e-03,  3.8694122e-03,  1.0452631e-03,
        -9.0916641e-05, -1.5222627e-03, -1.3253617e-03, -6.5038144e-04,
        -4.3336931e-04,  5.1391781e-03, -6.1555412e-03, -4.6909205e-04,
         1.5812786e-03,  4.7753882e-03,  6.4239150e-04, -2.3371857e-03,
         4.9051894e-03, -7.1727578e-03,  8.5053523e-04, -2.63266

In [67]:
x_new[0]

array([ 4.90587484e-03,  7.42763234e-03, -4.90260951e-04, -2.57627969e-03,
        8.43458436e-03, -1.65554741e-03,  6.02112757e-03, -1.17452419e-03,
        8.13173782e-03, -2.30359752e-03,  7.14591984e-03, -9.59941465e-03,
       -3.66904307e-03, -2.94727972e-03, -5.68767125e-03,  3.36751807e-04,
        7.76648615e-03, -5.07516600e-03, -7.29449908e-04,  2.24450231e-03,
        4.31937864e-04,  7.20499735e-03,  3.29957664e-04,  3.88500863e-04,
       -5.12075657e-03, -3.30026960e-04, -3.74833355e-03, -1.61338085e-03,
        1.36708189e-03, -3.56327882e-03, -5.17212786e-04, -4.94958740e-03,
       -3.09191109e-03, -5.95131144e-03, -6.04506768e-03, -8.66895169e-03,
        4.05815523e-03,  8.43399670e-03,  3.86941223e-03,  1.04526314e-03,
       -9.09166411e-05, -1.52226270e-03, -1.32536166e-03, -6.50381437e-04,
       -4.33369307e-04,  5.13917813e-03, -6.15554117e-03, -4.69092047e-04,
        1.58127863e-03,  4.77538817e-03,  6.42391504e-04, -2.33718567e-03,
        4.90518939e-03, -

In [44]:
x_new[0].shape

(100,)

In [45]:
## dependent features
## output features
y=pd.get_dummies(messages['label'])
y=y.iloc[:,0].values

In [46]:
messages

,label,message
0,ham,"Go until jurong point, crazy.. Available only ..."
1,ham,Ok lar... Joking wif u oni.
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...
3,ham,U dun say so early hor... U c already then say.
4,ham,"Nah I don't think he goes to usf, he lives aro..."
...,...,...
98,spam,Last chance to claim your reward.
99,ham,Can you share the lecture slides?
100,spam,"You have won ₹50,000 cash. Call now."
101,ham,Good night and sweet dreams.


In [47]:
messages.shape

(103, 2)

In [69]:
x[0]

array([ 4.9058748e-03,  7.4276323e-03, -4.9026095e-04, -2.5762797e-03,
        8.4345844e-03, -1.6555474e-03,  6.0211276e-03, -1.1745242e-03,
        8.1317378e-03, -2.3035975e-03,  7.1459198e-03, -9.5994147e-03,
       -3.6690431e-03, -2.9472797e-03, -5.6876712e-03,  3.3675181e-04,
        7.7664861e-03, -5.0751660e-03, -7.2944991e-04,  2.2445023e-03,
        4.3193786e-04,  7.2049974e-03,  3.2995766e-04,  3.8850086e-04,
       -5.1207566e-03, -3.3002696e-04, -3.7483335e-03, -1.6133809e-03,
        1.3670819e-03, -3.5632788e-03, -5.1721279e-04, -4.9495874e-03,
       -3.0919111e-03, -5.9513114e-03, -6.0450677e-03, -8.6689517e-03,
        4.0581552e-03,  8.4339967e-03,  3.8694122e-03,  1.0452631e-03,
       -9.0916641e-05, -1.5222627e-03, -1.3253617e-03, -6.5038144e-04,
       -4.3336931e-04,  5.1391781e-03, -6.1555412e-03, -4.6909205e-04,
        1.5812786e-03,  4.7753882e-03,  6.4239150e-04, -2.3371857e-03,
        4.9051894e-03, -7.1727578e-03,  8.5053523e-04, -2.6326622e-03,
      

In [71]:
df = pd.DataFrame()
for i in range(len(x)):
    row = pd.DataFrame(x[i].reshape(1, -1))
    df = pd.concat([df, row], ignore_index=True)

In [72]:
df.shape

(103, 100)

In [73]:
x[0].shape

(100,)

In [75]:
x[0].reshape(1,-1).shape

(1, 100)

In [77]:
df.head()

,0,1,2,3,4,5,6,7,8,9,...,90,91,92,93,94,95,96,97,98,99
0,0.004906,0.007428,-0.000490,-0.002576,0.008435,-0.001656,0.006021,-0.001175,0.008132,-0.002304,...,0.004319,0.001596,0.004061,-0.001507,0.002585,-0.000332,0.002640,0.006352,-0.007092,0.002689
1,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2,0.002612,0.003235,0.003095,0.001204,-0.003315,0.000640,0.005708,-0.000166,0.000179,-0.006746,...,0.001571,0.000630,-0.005350,0.004413,-0.000109,-0.003154,-0.002327,-0.000338,0.001922,0.001026
3,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
4,0.008165,-0.004443,0.008982,0.008260,-0.004435,0.000299,0.004276,-0.003921,-0.005566,-0.006517,...,0.002055,-0.004002,-0.008240,0.006281,-0.001940,-0.000673,-0.001772,-0.004535,0.004068,-0.004267


In [78]:
## independent feature
x=df

In [79]:
## train test split
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.20)

In [80]:
x_train.head()

,0,1,2,3,4,5,6,7,8,9,...,90,91,92,93,94,95,96,97,98,99
86,0.001931,-0.001269,0.000420,0.005517,0.000892,-0.002123,0.006300,0.003444,-0.005498,-0.001808,...,0.000339,-0.000626,0.001855,0.001847,0.005499,0.004340,0.001433,-0.002113,0.002246,0.001683
0,0.004906,0.007428,-0.000490,-0.002576,0.008435,-0.001656,0.006021,-0.001175,0.008132,-0.002304,...,0.004319,0.001596,0.004061,-0.001507,0.002585,-0.000332,0.002640,0.006352,-0.007092,0.002689
51,-0.002254,0.005192,0.000944,0.002182,-0.001798,-0.004469,-0.001704,0.003268,-0.002530,-0.001871,...,0.001355,0.000915,0.003889,-0.003222,-0.000025,-0.001524,-0.001104,-0.000936,-0.005158,0.006457
19,0.005576,0.008260,0.004085,-0.002529,0.002945,-0.000302,0.001927,0.002606,0.006619,-0.004004,...,0.007939,-0.001188,0.003427,0.003400,-0.000845,-0.004545,-0.001754,0.008530,-0.005996,0.007521
24,-0.002119,0.006469,-0.001359,-0.003436,0.006661,-0.000917,0.002699,0.004194,-0.002107,-0.002006,...,-0.000925,0.002746,0.004988,-0.003421,0.008159,0.004055,0.003209,-0.002944,0.003112,-0.006533


In [81]:
y_train

array([False,  True,  True,  True, False, False, False,  True, False,
        True, False, False, False,  True,  True, False,  True,  True,
        True,  True, False, False, False, False, False, False, False,
        True,  True,  True, False, False,  True,  True,  True,  True,
       False, False,  True, False, False,  True,  True, False,  True,
        True, False,  True, False,  True,  True,  True, False, False,
       False,  True,  True, False,  True, False, False,  True,  True,
        True, False,  True, False,  True, False,  True,  True,  True,
       False, False, False, False,  True, False, False, False,  True,
        True])

In [82]:
from sklearn.ensemble import RandomForestClassifier
classifier=RandomForestClassifier()

In [83]:
classifier.fit(x_train,y_train)

,"n_estimators n_estimators: int, default=100The number of trees in the forest... versionchanged:: 0.22 The default value of ``n_estimators`` changed from 10 to 100 in 0.22.",100
,"criterion criterion: {""gini"", ""entropy"", ""log_loss""}, default=""gini""The function to measure the quality of a split. Supported criteria are""gini"" for the Gini impurity and ""log_loss"" and ""entropy"" both for theShannon information gain, see :ref:`tree_mathematical_formulation`.Note: This parameter is tree-specific.",'gini'
,"max_depth max_depth: int, default=NoneThe maximum depth of the tree. If None, then nodes are expanded untilall leaves are pure or until all leaves contain less thanmin_samples_split samples.",None
,"min_samples_split min_samples_split: int or float, default=2The minimum number of samples required to split an internal node:- If int, then consider `min_samples_split` as the minimum number.- If float, then `min_samples_split` is a fraction and `ceil(min_samples_split * n_samples)` are the minimum number of samples for each split... versionchanged:: 0.18 Added float values for fractions.",2
,"min_samples_leaf min_samples_leaf: int or float, default=1The minimum number of samples required to be at a leaf node.A split point at any depth will only be considered if it leaves atleast ``min_samples_leaf`` training samples in each of the left andright branches. This may have the effect of smoothing the model,especially in regression.- If int, then consider `min_samples_leaf` as the minimum number.- If float, then `min_samples_leaf` is a fraction and `ceil(min_samples_leaf * n_samples)` are the minimum number of samples for each node... versionchanged:: 0.18 Added float values for fractions.",1
,"min_weight_fraction_leaf min_weight_fraction_leaf: float, default=0.0The minimum weighted fraction of the sum total of weights (of allthe input samples) required to be at a leaf node. Samples haveequal weight when sample_weight is not provided.",0.0
,"max_features max_features: {""sqrt"", ""log2"", None}, int or float, default=""sqrt""The number of features to consider when looking for the best split:- If int, then consider `max_features` features at each split.- If float, then `max_features` is a fraction and `max(1, int(max_features * n_features_in_))` features are considered at each split.- If ""sqrt"", then `max_features=sqrt(n_features)`.- If ""log2"", then `max_features=log2(n_features)`.- If None, then `max_features=n_features`... versionchanged:: 1.1 The default of `max_features` changed from `""auto""` to `""sqrt""`.Note: the search for a split does not stop until at least onevalid partition of the node samples is found, even if it requires toeffectively inspect more than ``max_features`` features.",'sqrt'
,"max_leaf_nodes max_leaf_nodes: int, default=NoneGrow trees with ``max_leaf_nodes`` in best-first fashion.Best nodes are defined as relative reduction in impurity.If None then unlimited number of leaf nodes.",None
,"min_impurity_decrease min_impurity_decrease: float, default=0.0A node will be split if this split induces a decrease of the impuritygreater than or equal to this value.The weighted impurity decrease equation is the following:: N_t / N * (impurity - N_t_R / N_t * right_impurity - N_t_L / N_t * left_impurity)where ``N`` is the total number of samples, ``N_t`` is the number ofsamples at the current node, ``N_t_L`` is the number of samples in theleft child, and ``N_t_R`` is the number of samples in the right child.``N``, ``N_t``, ``N_t_R`` and ``N_t_L`` all refer to the weighted sum,if ``sample_weight`` is passed... versionadded:: 0.19",0.0
,"bootstrap bootstrap: bool, default=TrueWhether bootstrap samples are used when building trees. If False, thewhole dataset is used to build each tree.",True
,"oob_score oob_score: bool or callable, default=FalseWhether to use out-of-bag samples to estimate the generalization score.By default, :func:`~sklearn.metrics.accuracy_score` is used.Provide a callable with signature `metric

In [85]:
x.isnull().sum()

0     0
1     0
2     0
3     0
4     0
     ..
95    0
96    0
97    0
98    0
99    0
Length: 100, dtype: int64

In [86]:
df['Output'] = y

In [87]:
df.head()

,0,1,2,3,4,5,6,7,8,9,...,91,92,93,94,95,96,97,98,99,Output
0,0.004906,0.007428,-0.000490,-0.002576,0.008435,-0.001656,0.006021,-0.001175,0.008132,-0.002304,...,0.001596,0.004061,-0.001507,0.002585,-0.000332,0.002640,0.006352,-0.007092,0.002689,True
1,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,True
2,0.002612,0.003235,0.003095,0.001204,-0.003315,0.000640,0.005708,-0.000166,0.000179,-0.006746,...,0.000630,-0.005350,0.004413,-0.000109,-0.003154,-0.002327,-0.000338,0.001922,0.001026,False
3,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,True
4,0.008165,-0.004443,0.008982,0.008260,-0.004435,0.000299,0.004276,-0.003921,-0.005566,-0.006517,...,-0.004002,-0.008240,0.006281,-0.001940,-0.000673,-0.001772,-0.004535,0.004068,-0.004267,True


In [88]:
df.dropna(inplace=True)

In [89]:
df.isnull().sum()

0         0
1         0
2         0
3         0
4         0
         ..
96        0
97        0
98        0
99        0
Output    0
Length: 101, dtype: int64

In [90]:
y=df['Output']

In [91]:
y_pred=classifier.predict(x_test)

In [92]:
from sklearn.metrics import accuracy_score,classification_report
print(accuracy_score(y_test,y_pred))

0.7619047619047619


In [93]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

       False       0.75      0.67      0.71         9
        True       0.77      0.83      0.80        12

    accuracy                           0.76        21
   macro avg       0.76      0.75      0.75        21
weighted avg       0.76      0.76      0.76        21

